version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
  pre_build:
    commands:
      - echo Checking for dotnet cli...
      - dotnet --version
      - echo Installing AWS Tools...
      - dotnet tool install -g Amazon.Lambda.Tools
      - echo Done
  build:
    commands:
      - echo Build started on `date`
      - echo Installing npm packages...
      - cd cdk
      - npm i
      - npm run build
      - cd ..
      - echo "Building project app..."
      - cd src/aws-cd-pipeline/
      - dotnet build
      - cd ../..
  post_build:
    commands:
      - echo Publishing lambda packages...
      - cd src/aws-cd-pipeline/
      - dotnet lambda package
      - cd ..
      - echo Build completed on `date`
#  pre_deploy:
#    commands:
#      - cdk diff
#  deploy:
#    commands:
#      - cdk deploy
#artifacts:
#  files:
#    - target/messageUtil-1.0.jar