AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  CdkSamAppDeployAspNetCoreFunctionSD1XDLCUGNUW:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: 'aws-cd-pipeline::aws_cd_pipeline.LambdaEntryPoint::FunctionHandlerAsync'
      Runtime: dotnetcore2.1
      CodeUri: .
      Description: ''
      MemorySize: 256
      Timeout: 30
      Role: >-
        arn:aws:iam::366072108453:role/CdkSamAppDeploy-AspNetCoreFunctionRole-1AV9W3EEB6FSB
      Events:
        Api1:
          Type: Api
          Properties:
            Path: /
            Method: ANY
        Api2:
          Type: Api
          Properties:
            Path: '/{proxy+}'
            Method: ANY
      Environment:
        Variables:
          AppS3Bucket: cdksamappdeploy-bucket-10uqzb20rz4h2
      Tags:
        AWSServerlessAppNETCore: 'true'
